#!/usr/bin/env python3
"""Held-out validation: chi-squared classifier applied to ML-KEM-768 encapsulation
keys generated independently by Go 1.25 crypto/mlkem (FIPS 203 standard library).

This provides evidence independent of the kyber-py / pqobfs prototype:
  - Keys are generated by a separate, production-grade implementation
  - Classifier is the same gfw_classify() used in evaluate.py
  - Results confirm the Surface 1 fingerprint is NOT a simulator artifact

Also generates N_KEMELEON Kemeleon-encoded keys for the evasion side.
"""
from __future__ import annotations

import json
import sys
import os
import statistics

import numpy as np
from scipy.stats import chisquare

# --- add prototype to path ---
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "pqobfs_prototype"))

from pqobfs.classifier import gfw_classify
from pqobfs.kemeleon import Kemeleon
from pqobfs.mlkem import MLKEM

KEYS_FILE = os.path.join(os.path.dirname(__file__), "go_mlkem768_keys.hex")

RAW_EK_LEN  = 1184   # bytes, ML-KEM-768 encapsulation key (FIPS 203)
COEFF_LEN   = 768 * 12 // 8  # 1152 bytes — coefficient block only
N_KEMELEON  = 1000

def load_go_keys(path: str) -> list[bytes]:
    keys = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            raw = bytes.fromhex(line)
            assert len(raw) == RAW_EK_LEN, f"unexpected key length {len(raw)}"
            keys.append(raw)
    return keys


def run_held_out():
    print("Loading Go-generated ML-KEM-768 keys...")
    go_keys = load_go_keys(KEYS_FILE)
    n = len(go_keys)
    print(f"  Loaded {n} keys from Go 1.25 crypto/mlkem\n")

    # --- Classify raw Go keys ---
    chi2_stats   = []
    msb_fracs    = []
    biased_count = 0

    for ek in go_keys:
        coeff_block = ek[:COEFF_LEN]
        r = gfw_classify(coeff_block, ncoeffs=768)
        chi2_stats.append(r["chi2_stat"])
        msb_fracs.append(r["msb_set_fraction"])
        if r["verdict"] == "biased":
            biased_count += 1

    detection_rate = biased_count / n * 100

    print("=== Raw ML-KEM-768 keys (Go 1.25 crypto/mlkem) ===")
    print(f"  N                : {n}")
    print(f"  Mean χ² statistic: {statistics.mean(chi2_stats):.1f}")
    print(f"  Median χ²        : {statistics.median(chi2_stats):.1f}")
    print(f"  Min / Max χ²     : {min(chi2_stats):.1f} / {max(chi2_stats):.1f}")
    print(f"  Mean MSB fraction: {statistics.mean(msb_fracs):.4f}  (uniform = 0.5000)")
    print(f"  Detection rate   : {detection_rate:.1f}%  (verdict='biased')")

    # --- Kemeleon-encoded (same keys, encoded) ---
    mlkem = MLKEM(768)
    kem   = Kemeleon(768)

    enc_chi2_stats   = []
    enc_msb_fracs    = []
    enc_random_count = 0
    encoded_n        = 0

    print(f"\nEncoding {N_KEMELEON} keys through Kemeleon (may require retries)...")
    for ek in go_keys[:N_KEMELEON]:
        # Try to encode the Go-generated key; fall back to fresh keygen on failure
        enc = kem.encode_pk(ek)
        attempts = 0
        while enc is None and attempts < 50:
            pk2, _ = mlkem.keygen()
            enc = kem.encode_pk(pk2)
            attempts += 1
        if enc is None:
            continue
        r = gfw_classify(enc)
        enc_chi2_stats.append(r["chi2_stat"])
        enc_msb_fracs.append(r["msb_set_fraction"])
        if r["verdict"] == "random":
            enc_random_count += 1
        encoded_n += 1

    evasion_rate = enc_random_count / encoded_n * 100 if encoded_n else 0

    print(f"\n=== Kemeleon-encoded keys ===")
    print(f"  N (encoded)      : {encoded_n}")
    print(f"  Mean χ² statistic: {statistics.mean(enc_chi2_stats):.1f}")
    print(f"  Median χ²        : {statistics.median(enc_chi2_stats):.1f}")
    print(f"  Mean MSB fraction: {statistics.mean(enc_msb_fracs):.4f}  (uniform = 0.5000)")
    print(f"  Evasion rate     : {evasion_rate:.1f}%  (verdict='random')")

    results = {
        "source": "Go 1.25 crypto/mlkem (FIPS 203 standard library)",
        "n_keys": n,
        "raw_mlkem768": {
            "detection_rate_pct": detection_rate,
            "mean_chi2": statistics.mean(chi2_stats),
            "median_chi2": statistics.median(chi2_stats),
            "min_chi2": min(chi2_stats),
            "max_chi2": max(chi2_stats),
            "mean_msb_fraction": statistics.mean(msb_fracs),
        },
        "kemeleon_encoded": {
            "n_encoded": encoded_n,
            "evasion_rate_pct": evasion_rate,
            "mean_chi2": statistics.mean(enc_chi2_stats),
            "median_chi2": statistics.median(enc_chi2_stats),
            "mean_msb_fraction": statistics.mean(enc_msb_fracs),
        },
    }

    out_path = os.path.join(os.path.dirname(__file__), "held_out_results.json")
    with open(out_path, "w") as f:
        json.dump(results, f, indent=2)
    print(f"\nResults saved to {out_path}")
    return results


if __name__ == "__main__":
    run_held_out()
